### ISSUE TITLE
Suggestion: Update Theme Schemes

### ISSUE THREAD

**Issue by RavenVex** [exordium-dev/exordium#18] opened 2020-01-31 22:05 UTC
**Describe the suggestion in detail:**
I think that there should be new color schemes incorporated in the app. The colors that are used now are mostly dull and boring. 

**How it can be implemented into the software:**
Just simple edits to the SASS main theme and it will update all colors within the design.

**What are the benefits to this addition:**
If the color schemes were to be changed, it could give the app a better look in terms of a welcoming yet calming feeling. Finding a way to add some colors that are brighter than what you have, could make some users experience with the app different and more enjoyable.

**Some examples:**

![image](https://user-images.githubusercontent.com/60240162/73577755-c1a0d380-444b-11ea-903b-e0335a8a33a5.png)![image](https://user-images.githubusercontent.com/60240162/73577511-0ed07580-444b-11ea-9a35-405debcbb61f.png)![image](https://user-images.githubusercontent.com/60240162/73577459-ec3e5c80-444a-11ea-8b8e-5d062944e4cf.png)

**Comment by tvOdyssey** [comment] 2020-02-01 03:45
This is basically a duplicate of my suggestion, #17. Try and post your ideas on that issue instead of creating a brand new one. I'll close this issue now.

**Closed by tvOdyssey** 2020-02-01 03:45 UTC
